version: "3.7"
services:
  # Storage
  redis:
    image: redis
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin123
  # Services
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '1987:80'
  client:
    restart: always
    build:
      context: ./client
    ports:
      - "3000:3000"
  api:
    restart: always
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: '6379'
      PGHOST: postgres
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: admin123
      PGPORT: '5432'
  worker:
    restart: always
    build:
      context: ./worker
    environment:
      REDIS_HOST: redis
      REDIS_PORT: '6379'